spring:
  application:
    name: bookstore-app-c
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  messages:
    basename: i18n/base/error_zh_CN,i18n/auth/error_zh_CN,i18n/company/error_zh_CN,i18n/company/info_zh_CN,i18n/saas/job/error_zh_CN,i18n/yun/recommend/error_zh_CN,i18n/yun/employee/error_zh_CN,i18n/yun/irecommend/error_zh_CN,i18n/yun/recommend/info_zh_CN
    encoding: UTF-8

  jackson:
    serialization:
      write-dates-as-timestamps: true

#===============================redis配置 begin=============================
  redis:
    host: redis.linkun.com
    port: 6379
#    password: linkun123
    database: 1
    timeout: 120000
    lettuce:
      pool:
        max-active: 50
        max-idle: 30
        min-idle: 10
        max-wait: 12000
#===============================redis配置 end===============================

#===============================连接池配置 begin=============================
  datasource:
#    url: jdbc:mysql://dphzmy-j9plohtrbtu3hmen-pub.proxy.dms.aliyuncs.com:3306/bookstore?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://127.0.0.1:3306/bookstore?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: kIfE9BDHUBKSk9lGgruxQ9Q4
    password: s3XAPWO0gYEKr3Yh1RZo6EAhHSpPNL
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: 5
      # 连接池允许的最大连接数
      maximum-pool-size: 10
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
#  datasource:
#    dynamic:
#      primary: linkun #设置默认的数据源或者数据源组,默认值即为master
#      strict: false
#      datasource:
#        linkun:
#          url: jdbc:mysql://dphzmy-j9plohtrbtu3hmen-pub.proxy.dms.aliyuncs.com:3306/bookstore?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
#          username: kIfE9BDHUBKSk9lGgruxQ9Q4
#          password: s3XAPWO0gYEKr3Yh1RZo6EAhHSpPNL
#          driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      # 连接池最小空闲连接数
#      minimum-idle: 5
#      # 连接池允许的最大连接数
#      maximum-pool-size: 10
#      # 等待连接池分配连接的最大时长（毫秒）
#      connection-timeout: 30000
#===============================连接池配置 end===============================

mybatis-plus:
  mapper-locations: classpath*:**/sqlmap/**/*.xml

logging:
  config: classpath:log4j/log4j2-${spring.profiles.active}.xml